name: Go Playground Unit Tests
on: [push]
jobs:
  my-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.16.0'
        run: go test
